# Generated by Django 3.1.7 on 2021-05-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name', models.CharField(max_length=30)),
                ('poster', models.ImageField(upload_to='posters')),
                ('actor_name', models.CharField(choices=[('Anushka', 'Anushka'), ('Kajal ', 'Kajal'), ('Samantha', 'Samantha'), ('Rakul', 'Rakul')], max_length=20)),
                ('trailer', models.FileField(upload_to='trailers')),
            ],
        ),
    ]
