# Generated by Django 3.1.7 on 2021-05-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actress_name',
            field=models.CharField(choices=[('Anushka', 'Anushka'), ('Kajal ', 'Kajal'), ('Samantha', 'Samantha'), ('Rakul', 'Rakul')], default='Missing', max_length=20),
        ),
        migrations.AlterField(
            model_name='movie',
            name='actor_name',
            field=models.CharField(choices=[('Balakrishna', 'Balakrishna'), ('Jr.Ntr', 'Jr.Ntr'), ('MaheshBabu', 'MaheshBabu'), ('Prabhas', 'Prabhas')], default='Missing', max_length=20),
        ),
    ]
