# Generated by Django 3.1.7 on 2021-05-12 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('mobileno', models.CharField(max_length=12)),
            ],
        ),
    ]
